### ISSUE TITLE
小鹤双拼

### ISSUE THREAD

**Issue by ghost** [controlledentropy/RIME_flypySchema_xhup-doublepinyinflypy#1]
小鹤双拼rime方案在小鹤双拼的官网的网盘里面就有。

**Comment by controlledentropy** [comment]
> 小鹤双拼rime方案在小鹤双拼的官网的网盘里面就有。

没错。但是小鹤网盘没有提供RIME整合双拼和音形的方案。我是从双拼过渡到音形的，相信还有很多新人也是先熟悉双拼然后引入形码的。而且在形码学习初期开始相当长一段时间估计输入速率都没法企及双拼，甚至很多场景下双拼是优于形码的。

我之前也用过PIME和小鹤的win7音形方案，感觉没有自己搞RIME方案踏实简洁，而且小鹤官网的音形输入法会触发很多应用的bug；至于PIME嘛，也有类似的问题且主要给人的感觉比较臃肿。现在一个RIME两套方案互切很舒服。

折腾和很久之后出来了这套方案，丢出来给有同样需求的人一起用。

不过在安卓上没能实现TRIME的双拼和音形互切，暂时是同文增强+小鹤基于trime改的flypy输入法。两套输入法虽然同源但现在还是没有能把两个输入法的方案，快捷键自定和皮肤UI搞到一起去……

**Comment by ghost** [comment]
哦，原来是这样，我以为你说没有音形方案，感谢你提供的这套方案文件，单音的文件的确难找，我是开始从其它输入法学的音，后面就在佛振和鹤大那里找到了音形了，初学者确实需要在音和音形之间转换，感谢！

在 2021年4月2日星期五，Michael Clayton ***@***.***> 写道：
> 小鹤双拼rime方案在小鹤双拼的官网的网盘里面就有。
>
>
没错。但是小鹤网盘没有提供RIME整合双拼和音形的方案。我是从双拼过渡到音形的，相信还有很多新人也是先熟悉双拼然后引入形码的。而且在形码学习初期开始相当长一段时间估计输入速率都没法企及双拼，甚至很多场景下双拼是优于形码的。
>
>
我之前也用过PIME和小鹤的win7音形方案，感觉没有自己搞RIME方案踏实简洁，而且小鹤官网的音形输入法会触发很多应用的bug；至于PIME嘛，也有类似的问题且主要给人的感觉比较臃肿。现在一个RIME两套方案互切很舒服。
>
> 折腾和很久之后出来了这套方案，丢出来给有同样需求的人一起用。
>
>
不过在安卓上没能实现TRIME的双拼和音形互切，暂时是同文增强+小鹤基于trime改的flypy输入法。两套输入法虽然同源但现在还是没有能把两个输入法的方案，快捷键自定和皮肤UI搞到一起去……
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/3GUhE5GVUN8O8_n28wQSIiyOzjn_P4hypA2WC6mho0z1aOlaN0d3KuI6KJXs6E7y8DNgm3th_nPHA75Ts2yoyixtSHlMRtitYMvhZBcepkvv1MB6AKFu8DKgWRYbfdwTrt9zkkFJ6ODUcxX7U9e-xIo3I6LzVOpwXS6RweCjCDOpWboUq3I8yRbBMrv_qcREgGlZOnsdAP01ifN6RAjJSAPkG-YDUofuv-XTsW4VRw=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF334KV5TPD5UW63P43TGVWKNA5CNFSM42HHHLNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGBV65TY.gif>
